name: Setup Node.js, pnpm and dependencies
description: Setup Node.js, pnpm and dependencies
inputs:
  token:
    description: Github token
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install ffmpeg
      if: runner.os == 'Linux'
      shell: 'bash'
      run: |
        sudo add-apt-repository ppa:ubuntuhandbook1/ffmpeg7 -y
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        token: ${{ inputs.token }}
        check-latest: true
        node-version-file: '.nvmrc'

    - name: Install pnpm deps
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      env:
        NODE_ENV: debug
        GITHUB_TOKEN: ${{ inputs.token }}
      run: pnpm i --frozen-lockfile
